//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELG.DAL.DbEntityLearner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Microsoft.Extensions.Configuration;
    
    public partial class learnerDBEntities : DbContext
    {
        public static IConfiguration _configuration { get; set; }

        public learnerDBEntities()
            : base(GetConnectionString())
        {
        }

        private static string GetConnectionString()
        {
            if (_configuration != null)
            {
                var connStr = _configuration.GetConnectionString("learnerDBEntities");
                if (!string.IsNullOrEmpty(connStr))
                {
                    System.Diagnostics.Debug.WriteLine($"[learnerDBEntities] Using connection string from configuration");
                    return connStr;
                }
                else
                {
                    System.Diagnostics.Debug.WriteLine($"[learnerDBEntities] Configuration exists but connection string 'learnerDBEntities' not found");
                }
            }
            else
            {
                System.Diagnostics.Debug.WriteLine($"[learnerDBEntities] Configuration is NULL - falling back to app.config");
            }

            return "name=learnerDBEntities";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCourse> tbCourses { get; set; }
        public virtual DbSet<lms_widget_details> lms_widget_details { get; set; }
        public virtual DbSet<tbOrganisationDomainDetail> tbOrganisationDomainDetails { get; set; }
    
        public virtual int lms_learner_AssignCoursestoContact(Nullable<long> contactid, string courseids, ObjectParameter retval, ObjectParameter courseList)
        {
            var contactidParameter = contactid.HasValue ?
                new ObjectParameter("contactid", contactid) :
                new ObjectParameter("contactid", typeof(long));
    
            var courseidsParameter = courseids != null ?
                new ObjectParameter("courseids", courseids) :
                new ObjectParameter("courseids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_AssignCoursestoContact", contactidParameter, courseidsParameter, retval, courseList);
        }
    
        public virtual ObjectResult<Nullable<int>> lms_learner_check_admin_rights(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("lms_learner_check_admin_rights", useridParameter);
        }
    
        public virtual ObjectResult<lms_learner_check_unassignedCoursesWithNoLicences_Result> lms_learner_check_unassignedCoursesWithNoLicences(Nullable<long> learner)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_check_unassignedCoursesWithNoLicences_Result>("lms_learner_check_unassignedCoursesWithNoLicences", learnerParameter);
        }
    
        public virtual int lms_learner_courseSessionEndRecord(Nullable<long> intcontactid, Nullable<long> intcourseid)
        {
            var intcontactidParameter = intcontactid.HasValue ?
                new ObjectParameter("intcontactid", intcontactid) :
                new ObjectParameter("intcontactid", typeof(long));
    
            var intcourseidParameter = intcourseid.HasValue ?
                new ObjectParameter("intcourseid", intcourseid) :
                new ObjectParameter("intcourseid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_courseSessionEndRecord", intcontactidParameter, intcourseidParameter);
        }
    
        public virtual int lms_learner_create_accidentincident_response(Nullable<long> contactid, Nullable<long> accidentincidentid, string response, Nullable<long> createdBy, string reportedby, string reportedFor, string incidentHappendOn, Nullable<int> isEmployee, Nullable<int> isPermitted, ObjectParameter id)
        {
            var contactidParameter = contactid.HasValue ?
                new ObjectParameter("contactid", contactid) :
                new ObjectParameter("contactid", typeof(long));
    
            var accidentincidentidParameter = accidentincidentid.HasValue ?
                new ObjectParameter("accidentincidentid", accidentincidentid) :
                new ObjectParameter("accidentincidentid", typeof(long));
    
            var responseParameter = response != null ?
                new ObjectParameter("response", response) :
                new ObjectParameter("response", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(long));
    
            var reportedbyParameter = reportedby != null ?
                new ObjectParameter("reportedby", reportedby) :
                new ObjectParameter("reportedby", typeof(string));
    
            var reportedForParameter = reportedFor != null ?
                new ObjectParameter("reportedFor", reportedFor) :
                new ObjectParameter("reportedFor", typeof(string));
    
            var incidentHappendOnParameter = incidentHappendOn != null ?
                new ObjectParameter("incidentHappendOn", incidentHappendOn) :
                new ObjectParameter("incidentHappendOn", typeof(string));
    
            var isEmployeeParameter = isEmployee.HasValue ?
                new ObjectParameter("isEmployee", isEmployee) :
                new ObjectParameter("isEmployee", typeof(int));
    
            var isPermittedParameter = isPermitted.HasValue ?
                new ObjectParameter("isPermitted", isPermitted) :
                new ObjectParameter("isPermitted", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_create_accidentincident_response", contactidParameter, accidentincidentidParameter, responseParameter, createdByParameter, reportedbyParameter, reportedForParameter, incidentHappendOnParameter, isEmployeeParameter, isPermittedParameter, id);
        }
    
        public virtual int lms_learner_create_Incident_ResponseEvidence(Nullable<long> intResponseId, string strImagePath, ObjectParameter retval)
        {
            var intResponseIdParameter = intResponseId.HasValue ?
                new ObjectParameter("intResponseId", intResponseId) :
                new ObjectParameter("intResponseId", typeof(long));
    
            var strImagePathParameter = strImagePath != null ?
                new ObjectParameter("strImagePath", strImagePath) :
                new ObjectParameter("strImagePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_create_Incident_ResponseEvidence", intResponseIdParameter, strImagePathParameter, retval);
        }
    
        public virtual int lms_learner_create_RA_AnswerEvidence(Nullable<long> intAnswerId, string strEvidencePath, ObjectParameter id)
        {
            var intAnswerIdParameter = intAnswerId.HasValue ?
                new ObjectParameter("intAnswerId", intAnswerId) :
                new ObjectParameter("intAnswerId", typeof(long));
    
            var strEvidencePathParameter = strEvidencePath != null ?
                new ObjectParameter("strEvidencePath", strEvidencePath) :
                new ObjectParameter("strEvidencePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_create_RA_AnswerEvidence", intAnswerIdParameter, strEvidencePathParameter, id);
        }
    
        public virtual int lms_learner_createClassroomRequest(Nullable<long> @class, Nullable<long> learner, Nullable<long> company, ObjectParameter id)
        {
            var classParameter = @class.HasValue ?
                new ObjectParameter("class", @class) :
                new ObjectParameter("class", typeof(long));
    
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var companyParameter = company.HasValue ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_createClassroomRequest", classParameter, learnerParameter, companyParameter, id);
        }
    
        public virtual int lms_learner_createLearner(string firstname, string title, string lastname, string employeeNumber, string email, Nullable<long> organisation, Nullable<long> location, Nullable<long> department, ObjectParameter id)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var employeeNumberParameter = employeeNumber != null ?
                new ObjectParameter("employeeNumber", employeeNumber) :
                new ObjectParameter("employeeNumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var organisationParameter = organisation.HasValue ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(long));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(long));
    
            var departmentParameter = department.HasValue ?
                new ObjectParameter("department", department) :
                new ObjectParameter("department", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_createLearner", firstnameParameter, titleParameter, lastnameParameter, employeeNumberParameter, emailParameter, organisationParameter, locationParameter, departmentParameter, id);
        }
    
        public virtual int lms_learner_createRAResponse(Nullable<long> answerid, Nullable<long> optionid, string note)
        {
            var answeridParameter = answerid.HasValue ?
                new ObjectParameter("answerid", answerid) :
                new ObjectParameter("answerid", typeof(long));
    
            var optionidParameter = optionid.HasValue ?
                new ObjectParameter("optionid", optionid) :
                new ObjectParameter("optionid", typeof(long));
    
            var noteParameter = note != null ?
                new ObjectParameter("note", note) :
                new ObjectParameter("note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_createRAResponse", answeridParameter, optionidParameter, noteParameter);
        }
    
        public virtual int lms_learner_createRiskAssessmentRecord(Nullable<long> course, Nullable<long> learner, ObjectParameter id)
        {
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_createRiskAssessmentRecord", courseParameter, learnerParameter, id);
        }
    
        public virtual int lms_learner_FinishRiskAssessment(Nullable<long> incontactid, Nullable<long> intcourseid)
        {
            var incontactidParameter = incontactid.HasValue ?
                new ObjectParameter("incontactid", incontactid) :
                new ObjectParameter("incontactid", typeof(long));
    
            var intcourseidParameter = intcourseid.HasValue ?
                new ObjectParameter("intcourseid", intcourseid) :
                new ObjectParameter("intcourseid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_FinishRiskAssessment", incontactidParameter, intcourseidParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_accidentIncidentQues_Result> lms_learner_get_accidentIncidentQues(Nullable<long> accidentId)
        {
            var accidentIdParameter = accidentId.HasValue ?
                new ObjectParameter("accidentId", accidentId) :
                new ObjectParameter("accidentId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_accidentIncidentQues_Result>("lms_learner_get_accidentIncidentQues", accidentIdParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_certificate_record_Result> lms_learner_get_certificate_record(Nullable<long> recordid)
        {
            var recordidParameter = recordid.HasValue ?
                new ObjectParameter("recordid", recordid) :
                new ObjectParameter("recordid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_certificate_record_Result>("lms_learner_get_certificate_record", recordidParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_companyContractorInfo_Result> lms_learner_get_companyContractorInfo(Nullable<long> org)
        {
            var orgParameter = org.HasValue ?
                new ObjectParameter("org", org) :
                new ObjectParameter("org", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_companyContractorInfo_Result>("lms_learner_get_companyContractorInfo", orgParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_dash_course_completion_Result> lms_learner_get_dash_course_completion(Nullable<long> learner)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_dash_course_completion_Result>("lms_learner_get_dash_course_completion", learnerParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_dash_HeaderInfo_Result> lms_learner_get_dash_HeaderInfo(Nullable<long> organisation, Nullable<long> learner)
        {
            var organisationParameter = organisation.HasValue ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(long));
    
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_dash_HeaderInfo_Result>("lms_learner_get_dash_HeaderInfo", organisationParameter, learnerParameter);
        }
    
        public virtual ObjectResult<string> lms_learner_get_dash_notification()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("lms_learner_get_dash_notification");
        }
    
        public virtual ObjectResult<lms_learner_get_dash_WeeklyProgress_Result> lms_learner_get_dash_WeeklyProgress(Nullable<long> learner)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_dash_WeeklyProgress_Result>("lms_learner_get_dash_WeeklyProgress", learnerParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_dash_YearlyCompletion_Result> lms_learner_get_dash_YearlyCompletion(Nullable<long> learner)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_dash_YearlyCompletion_Result>("lms_learner_get_dash_YearlyCompletion", learnerParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_LearnerSSOInfo_Result> lms_learner_get_LearnerSSOInfo(string learner)
        {
            var learnerParameter = learner != null ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_LearnerSSOInfo_Result>("lms_learner_get_LearnerSSOInfo", learnerParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_progress_history_Result> lms_learner_get_progress_history(Nullable<long> learner, Nullable<long> course)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_progress_history_Result>("lms_learner_get_progress_history", learnerParameter, courseParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_reportedIncidents_Result> lms_learner_get_reportedIncidents(string search, Nullable<long> contactid, string sortCol, string sortDir)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var contactidParameter = contactid.HasValue ?
                new ObjectParameter("contactid", contactid) :
                new ObjectParameter("contactid", typeof(long));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_reportedIncidents_Result>("lms_learner_get_reportedIncidents", searchParameter, contactidParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_learner_GetAdminOrgRegSettings_Result> lms_learner_GetAdminOrgRegSettings(Nullable<long> intOrganisationID)
        {
            var intOrganisationIDParameter = intOrganisationID.HasValue ?
                new ObjectParameter("intOrganisationID", intOrganisationID) :
                new ObjectParameter("intOrganisationID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_GetAdminOrgRegSettings_Result>("lms_learner_GetAdminOrgRegSettings", intOrganisationIDParameter);
        }
    
        public virtual ObjectResult<lms_learner_getAllAcceptedClassrooms_Result> lms_learner_getAllAcceptedClassrooms(Nullable<long> company, Nullable<long> learner, string classroom)
        {
            var companyParameter = company.HasValue ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(long));
    
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var classroomParameter = classroom != null ?
                new ObjectParameter("classroom", classroom) :
                new ObjectParameter("classroom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getAllAcceptedClassrooms_Result>("lms_learner_getAllAcceptedClassrooms", companyParameter, learnerParameter, classroomParameter);
        }
    
        public virtual ObjectResult<lms_learner_getAllAnouncments_Result> lms_learner_getAllAnouncments(Nullable<long> learner, Nullable<long> organisation, Nullable<long> announcementId, string announcement)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var organisationParameter = organisation.HasValue ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(long));
    
            var announcementIdParameter = announcementId.HasValue ?
                new ObjectParameter("announcementId", announcementId) :
                new ObjectParameter("announcementId", typeof(long));
    
            var announcementParameter = announcement != null ?
                new ObjectParameter("announcement", announcement) :
                new ObjectParameter("announcement", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getAllAnouncments_Result>("lms_learner_getAllAnouncments", learnerParameter, organisationParameter, announcementIdParameter, announcementParameter);
        }
    
        public virtual ObjectResult<lms_learner_getAllClassrooms_Result> lms_learner_getAllClassrooms(Nullable<long> company, Nullable<long> learner, string classroom)
        {
            var companyParameter = company.HasValue ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(long));
    
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var classroomParameter = classroom != null ?
                new ObjectParameter("classroom", classroom) :
                new ObjectParameter("classroom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getAllClassrooms_Result>("lms_learner_getAllClassrooms", companyParameter, learnerParameter, classroomParameter);
        }
    
        public virtual ObjectResult<lms_learner_getAllCourses_Result> lms_learner_getAllCourses(Nullable<long> learner, string course, string sort)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var courseParameter = course != null ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(string));
    
            var sortParameter = sort != null ?
                new ObjectParameter("sort", sort) :
                new ObjectParameter("sort", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getAllCourses_Result>("lms_learner_getAllCourses", learnerParameter, courseParameter, sortParameter);
        }
    
        public virtual ObjectResult<lms_learner_getAllDocuments_Result> lms_learner_getAllDocuments(string search, Nullable<int> category, Nullable<long> company, Nullable<long> learner, Nullable<int> status)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var categoryParameter = category.HasValue ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(int));
    
            var companyParameter = company.HasValue ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(long));
    
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getAllDocuments_Result>("lms_learner_getAllDocuments", searchParameter, categoryParameter, companyParameter, learnerParameter, statusParameter);
        }
    
        public virtual ObjectResult<lms_learner_getAllRACourses_Result> lms_learner_getAllRACourses(Nullable<long> learner, Nullable<long> company, string course)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var companyParameter = company.HasValue ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(long));
    
            var courseParameter = course != null ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getAllRACourses_Result>("lms_learner_getAllRACourses", learnerParameter, companyParameter, courseParameter);
        }
    
        public virtual ObjectResult<lms_learner_getAllUnreadNotifications_Result> lms_learner_getAllUnreadNotifications(Nullable<long> learner, Nullable<long> company)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var companyParameter = company.HasValue ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getAllUnreadNotifications_Result>("lms_learner_getAllUnreadNotifications", learnerParameter, companyParameter);
        }
    
        public virtual ObjectResult<lms_learner_getCompanyInfo_Result> lms_learner_getCompanyInfo(string company)
        {
            var companyParameter = company != null ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getCompanyInfo_Result>("lms_learner_getCompanyInfo", companyParameter);
        }
    
        public virtual ObjectResult<lms_learner_getCoursesForAutoAssignement_Result> lms_learner_getCoursesForAutoAssignement(Nullable<long> location, Nullable<long> department)
        {
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(long));
    
            var departmentParameter = department.HasValue ?
                new ObjectParameter("department", department) :
                new ObjectParameter("department", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getCoursesForAutoAssignement_Result>("lms_learner_getCoursesForAutoAssignement", locationParameter, departmentParameter);
        }
    
        public virtual ObjectResult<lms_learner_getLoginDetails_Result> lms_learner_getLoginDetails(Nullable<long> organisation, string useremail, string pwd, Nullable<bool> masterPwd)
        {
            var organisationParameter = organisation.HasValue ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(long));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var masterPwdParameter = masterPwd.HasValue ?
                new ObjectParameter("masterPwd", masterPwd) :
                new ObjectParameter("masterPwd", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getLoginDetails_Result>("lms_learner_getLoginDetails", organisationParameter, useremailParameter, pwdParameter, masterPwdParameter);
        }
    
        public virtual ObjectResult<lms_learner_GetNewUserInfoOrResetPasswordInfo_Result> lms_learner_GetNewUserInfoOrResetPasswordInfo(Nullable<int> intContactID)
        {
            var intContactIDParameter = intContactID.HasValue ?
                new ObjectParameter("intContactID", intContactID) :
                new ObjectParameter("intContactID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_GetNewUserInfoOrResetPasswordInfo_Result>("lms_learner_GetNewUserInfoOrResetPasswordInfo", intContactIDParameter);
        }
    
        public virtual ObjectResult<lms_learner_getRAQuestion_Result> lms_learner_getRAQuestion(Nullable<long> learner, Nullable<long> course)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getRAQuestion_Result>("lms_learner_getRAQuestion", learnerParameter, courseParameter);
        }
    
        public virtual ObjectResult<lms_learner_getRAResponses_Result> lms_learner_getRAResponses(Nullable<long> learner, Nullable<long> course)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getRAResponses_Result>("lms_learner_getRAResponses", learnerParameter, courseParameter);
        }
    
        public virtual ObjectResult<lms_learner_getSessionUserInfo_Result> lms_learner_getSessionUserInfo(Nullable<long> user)
        {
            var userParameter = user.HasValue ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getSessionUserInfo_Result>("lms_learner_getSessionUserInfo", userParameter);
        }
    
        public virtual ObjectResult<lms_learner_getSSOLoginDetails_Result> lms_learner_getSSOLoginDetails(string useremail)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getSSOLoginDetails_Result>("lms_learner_getSSOLoginDetails", useremailParameter);
        }
    
        public virtual ObjectResult<lms_learner_GetUserShortDetailByUserID_Result> lms_learner_GetUserShortDetailByUserID(Nullable<int> intContactID)
        {
            var intContactIDParameter = intContactID.HasValue ?
                new ObjectParameter("intContactID", intContactID) :
                new ObjectParameter("intContactID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_GetUserShortDetailByUserID_Result>("lms_learner_GetUserShortDetailByUserID", intContactIDParameter);
        }
    
        public virtual ObjectResult<lms_learner_initializeModule_Result> lms_learner_initializeModule(Nullable<long> intcontactid, Nullable<long> intcourseid)
        {
            var intcontactidParameter = intcontactid.HasValue ?
                new ObjectParameter("intcontactid", intcontactid) :
                new ObjectParameter("intcontactid", typeof(long));
    
            var intcourseidParameter = intcourseid.HasValue ?
                new ObjectParameter("intcourseid", intcourseid) :
                new ObjectParameter("intcourseid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_initializeModule_Result>("lms_learner_initializeModule", intcontactidParameter, intcourseidParameter);
        }
    
        public virtual int lms_learner_insert_course_launch_record(Nullable<long> intContactId, string browser, string browserVersion, string os, string device, string browserDetails, Nullable<bool> isMobileDevice, Nullable<long> intCourseId, string course, ObjectParameter insertRecordId)
        {
            var intContactIdParameter = intContactId.HasValue ?
                new ObjectParameter("intContactId", intContactId) :
                new ObjectParameter("intContactId", typeof(long));
    
            var browserParameter = browser != null ?
                new ObjectParameter("browser", browser) :
                new ObjectParameter("browser", typeof(string));
    
            var browserVersionParameter = browserVersion != null ?
                new ObjectParameter("browserVersion", browserVersion) :
                new ObjectParameter("browserVersion", typeof(string));
    
            var osParameter = os != null ?
                new ObjectParameter("os", os) :
                new ObjectParameter("os", typeof(string));
    
            var deviceParameter = device != null ?
                new ObjectParameter("device", device) :
                new ObjectParameter("device", typeof(string));
    
            var browserDetailsParameter = browserDetails != null ?
                new ObjectParameter("browserDetails", browserDetails) :
                new ObjectParameter("browserDetails", typeof(string));
    
            var isMobileDeviceParameter = isMobileDevice.HasValue ?
                new ObjectParameter("isMobileDevice", isMobileDevice) :
                new ObjectParameter("isMobileDevice", typeof(bool));
    
            var intCourseIdParameter = intCourseId.HasValue ?
                new ObjectParameter("intCourseId", intCourseId) :
                new ObjectParameter("intCourseId", typeof(long));
    
            var courseParameter = course != null ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_insert_course_launch_record", intContactIdParameter, browserParameter, browserVersionParameter, osParameter, deviceParameter, browserDetailsParameter, isMobileDeviceParameter, intCourseIdParameter, courseParameter, insertRecordId);
        }
    
        public virtual int lms_learner_insert_Login_Details(Nullable<long> intContactId, string browser, string browserVersion, string os, string device, string browserDetails, Nullable<bool> isMobileDevice, ObjectParameter insertRecordId)
        {
            var intContactIdParameter = intContactId.HasValue ?
                new ObjectParameter("intContactId", intContactId) :
                new ObjectParameter("intContactId", typeof(long));
    
            var browserParameter = browser != null ?
                new ObjectParameter("browser", browser) :
                new ObjectParameter("browser", typeof(string));
    
            var browserVersionParameter = browserVersion != null ?
                new ObjectParameter("browserVersion", browserVersion) :
                new ObjectParameter("browserVersion", typeof(string));
    
            var osParameter = os != null ?
                new ObjectParameter("os", os) :
                new ObjectParameter("os", typeof(string));
    
            var deviceParameter = device != null ?
                new ObjectParameter("device", device) :
                new ObjectParameter("device", typeof(string));
    
            var browserDetailsParameter = browserDetails != null ?
                new ObjectParameter("browserDetails", browserDetails) :
                new ObjectParameter("browserDetails", typeof(string));
    
            var isMobileDeviceParameter = isMobileDevice.HasValue ?
                new ObjectParameter("isMobileDevice", isMobileDevice) :
                new ObjectParameter("isMobileDevice", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_insert_Login_Details", intContactIdParameter, browserParameter, browserVersionParameter, osParameter, deviceParameter, browserDetailsParameter, isMobileDeviceParameter, insertRecordId);
        }
    
        public virtual int lms_learner_ResetPasswordFlag(Nullable<int> intContactID)
        {
            var intContactIDParameter = intContactID.HasValue ?
                new ObjectParameter("intContactID", intContactID) :
                new ObjectParameter("intContactID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_ResetPasswordFlag", intContactIDParameter);
        }
    
        public virtual int lms_learner_setDocRead(Nullable<long> learner, Nullable<long> docid, Nullable<long> organisation, ObjectParameter retval)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var docidParameter = docid.HasValue ?
                new ObjectParameter("docid", docid) :
                new ObjectParameter("docid", typeof(long));
    
            var organisationParameter = organisation.HasValue ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_setDocRead", learnerParameter, docidParameter, organisationParameter, retval);
        }
    
        public virtual int lms_learner_setDocStatus(Nullable<long> learner, Nullable<long> docid, string status, ObjectParameter retval)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var docidParameter = docid.HasValue ?
                new ObjectParameter("docid", docid) :
                new ObjectParameter("docid", typeof(long));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_setDocStatus", learnerParameter, docidParameter, statusParameter, retval);
        }
    
        public virtual int lms_learner_setNotificationRead(Nullable<long> intContactID, Nullable<long> intAnnId, ObjectParameter retval)
        {
            var intContactIDParameter = intContactID.HasValue ?
                new ObjectParameter("intContactID", intContactID) :
                new ObjectParameter("intContactID", typeof(long));
    
            var intAnnIdParameter = intAnnId.HasValue ?
                new ObjectParameter("intAnnId", intAnnId) :
                new ObjectParameter("intAnnId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_setNotificationRead", intContactIDParameter, intAnnIdParameter, retval);
        }
    
        public virtual int lms_learner_startRiskAssessment(Nullable<long> incontactid, Nullable<long> intcourseid)
        {
            var incontactidParameter = incontactid.HasValue ?
                new ObjectParameter("incontactid", incontactid) :
                new ObjectParameter("incontactid", typeof(long));
    
            var intcourseidParameter = intcourseid.HasValue ?
                new ObjectParameter("intcourseid", intcourseid) :
                new ObjectParameter("intcourseid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_startRiskAssessment", incontactidParameter, intcourseidParameter);
        }
    
        public virtual int lms_learner_update_CourseProgressScore(Nullable<long> contactid, Nullable<long> courseid, Nullable<int> passingMarks, Nullable<int> scoredMarks)
        {
            var contactidParameter = contactid.HasValue ?
                new ObjectParameter("contactid", contactid) :
                new ObjectParameter("contactid", typeof(long));
    
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(long));
    
            var passingMarksParameter = passingMarks.HasValue ?
                new ObjectParameter("passingMarks", passingMarks) :
                new ObjectParameter("passingMarks", typeof(int));
    
            var scoredMarksParameter = scoredMarks.HasValue ?
                new ObjectParameter("scoredMarks", scoredMarks) :
                new ObjectParameter("scoredMarks", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_update_CourseProgressScore", contactidParameter, courseidParameter, passingMarksParameter, scoredMarksParameter);
        }
    
        public virtual int lms_learner_update_profilePic(Nullable<long> learner, byte[] profilePic, ObjectParameter update)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var profilePicParameter = profilePic != null ?
                new ObjectParameter("profilePic", profilePic) :
                new ObjectParameter("profilePic", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_update_profilePic", learnerParameter, profilePicParameter, update);
        }
    
        public virtual int lms_learner_updateCourseProgressRecord(Nullable<long> contactid, Nullable<long> courseid, string action, string value)
        {
            var contactidParameter = contactid.HasValue ?
                new ObjectParameter("contactid", contactid) :
                new ObjectParameter("contactid", typeof(long));
    
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(long));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_updateCourseProgressRecord", contactidParameter, courseidParameter, actionParameter, valueParameter);
        }
    
        public virtual int lms_learner_updateCourseProgressRecord_withSession(Nullable<long> contactid, Nullable<long> courseid, string strBookMark, string strStatus, string strSuspendData, Nullable<int> intScore, string sessionTime, ObjectParameter sendITPCertificate)
        {
            var contactidParameter = contactid.HasValue ?
                new ObjectParameter("contactid", contactid) :
                new ObjectParameter("contactid", typeof(long));
    
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(long));
    
            var strBookMarkParameter = strBookMark != null ?
                new ObjectParameter("strBookMark", strBookMark) :
                new ObjectParameter("strBookMark", typeof(string));
    
            var strStatusParameter = strStatus != null ?
                new ObjectParameter("strStatus", strStatus) :
                new ObjectParameter("strStatus", typeof(string));
    
            var strSuspendDataParameter = strSuspendData != null ?
                new ObjectParameter("strSuspendData", strSuspendData) :
                new ObjectParameter("strSuspendData", typeof(string));
    
            var intScoreParameter = intScore.HasValue ?
                new ObjectParameter("intScore", intScore) :
                new ObjectParameter("intScore", typeof(int));
    
            var sessionTimeParameter = sessionTime != null ?
                new ObjectParameter("sessionTime", sessionTime) :
                new ObjectParameter("sessionTime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_updateCourseProgressRecord_withSession", contactidParameter, courseidParameter, strBookMarkParameter, strStatusParameter, strSuspendDataParameter, intScoreParameter, sessionTimeParameter, sendITPCertificate);
        }
    
        public virtual int lms_learner_UpdatePassword(Nullable<int> intContactID, string pwd)
        {
            var intContactIDParameter = intContactID.HasValue ?
                new ObjectParameter("intContactID", intContactID) :
                new ObjectParameter("intContactID", typeof(int));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_UpdatePassword", intContactIDParameter, pwdParameter);
        }
    
        public virtual int lms_learner_updateSessionUserInfo(Nullable<long> learner, string firstname, string surname, string email, string empNo, ObjectParameter retval)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var empNoParameter = empNo != null ?
                new ObjectParameter("empNo", empNo) :
                new ObjectParameter("empNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_updateSessionUserInfo", learnerParameter, firstnameParameter, surnameParameter, emailParameter, empNoParameter, retval);
        }
    
        public virtual ObjectResult<lms_learner_validateCompanyNumber_Result> lms_learner_validateCompanyNumber(string useremail, string company)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_validateCompanyNumber_Result>("lms_learner_validateCompanyNumber", useremailParameter, companyParameter);
        }
    
        public virtual ObjectResult<lms_learner_getLoginDetails_byUserId_Result> lms_learner_getLoginDetails_byUserId(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getLoginDetails_byUserId_Result>("lms_learner_getLoginDetails_byUserId", useridParameter);
        }
    
        public virtual ObjectResult<lms_learner_getDocument_info_Result> lms_learner_getDocument_info(Nullable<int> docId, Nullable<long> learner)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("docId", docId) :
                new ObjectParameter("docId", typeof(int));
    
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_getDocument_info_Result>("lms_learner_getDocument_info", docIdParameter, learnerParameter);
        }
    
        public virtual ObjectResult<lms_global_getCompanyDomainInfo_Result> lms_global_getCompanyDomainInfo(string domain)
        {
            var domainParameter = domain != null ?
                new ObjectParameter("domain", domain) :
                new ObjectParameter("domain", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_global_getCompanyDomainInfo_Result>("lms_global_getCompanyDomainInfo", domainParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_widget_response_Result> lms_learner_get_widget_response(string que_guid, Nullable<long> user_id)
        {
            var que_guidParameter = que_guid != null ?
                new ObjectParameter("que_guid", que_guid) :
                new ObjectParameter("que_guid", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_widget_response_Result>("lms_learner_get_widget_response", que_guidParameter, user_idParameter);
        }
    
        public virtual int lms_learner_insert_widget_response(Nullable<long> learnerId, string queId, string response, string responseFor, ObjectParameter created)
        {
            var learnerIdParameter = learnerId.HasValue ?
                new ObjectParameter("learnerId", learnerId) :
                new ObjectParameter("learnerId", typeof(long));
    
            var queIdParameter = queId != null ?
                new ObjectParameter("queId", queId) :
                new ObjectParameter("queId", typeof(string));
    
            var responseParameter = response != null ?
                new ObjectParameter("response", response) :
                new ObjectParameter("response", typeof(string));
    
            var responseForParameter = responseFor != null ?
                new ObjectParameter("responseFor", responseFor) :
                new ObjectParameter("responseFor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_insert_widget_response", learnerIdParameter, queIdParameter, responseParameter, responseForParameter, created);
        }
    
        public virtual int lms_learner_resetProgress(Nullable<long> learner, Nullable<long> course, Nullable<long> recordId, ObjectParameter res)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            var recordIdParameter = recordId.HasValue ?
                new ObjectParameter("recordId", recordId) :
                new ObjectParameter("recordId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_resetProgress", learnerParameter, courseParameter, recordIdParameter, res);
        }
    
        public virtual ObjectResult<lms_learner_get_mac_widget_response_Result> lms_learner_get_mac_widget_response(string que_guid, Nullable<long> user_id)
        {
            var que_guidParameter = que_guid != null ?
                new ObjectParameter("que_guid", que_guid) :
                new ObjectParameter("que_guid", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_mac_widget_response_Result>("lms_learner_get_mac_widget_response", que_guidParameter, user_idParameter);
        }
    
        public virtual int lms_learner_insert_mac_widget_response(Nullable<long> learnerId, string queId, string response1, string response2, string response3, ObjectParameter created)
        {
            var learnerIdParameter = learnerId.HasValue ?
                new ObjectParameter("learnerId", learnerId) :
                new ObjectParameter("learnerId", typeof(long));
    
            var queIdParameter = queId != null ?
                new ObjectParameter("queId", queId) :
                new ObjectParameter("queId", typeof(string));
    
            var response1Parameter = response1 != null ?
                new ObjectParameter("response1", response1) :
                new ObjectParameter("response1", typeof(string));
    
            var response2Parameter = response2 != null ?
                new ObjectParameter("response2", response2) :
                new ObjectParameter("response2", typeof(string));
    
            var response3Parameter = response3 != null ?
                new ObjectParameter("response3", response3) :
                new ObjectParameter("response3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_insert_mac_widget_response", learnerIdParameter, queIdParameter, response1Parameter, response2Parameter, response3Parameter, created);
        }
    
        public virtual int lms_learner_insert_mac_widget_feedback(Nullable<long> learnerId, string queId, string feedback, string feedbackText, ObjectParameter created)
        {
            var learnerIdParameter = learnerId.HasValue ?
                new ObjectParameter("learnerId", learnerId) :
                new ObjectParameter("learnerId", typeof(long));
    
            var queIdParameter = queId != null ?
                new ObjectParameter("queId", queId) :
                new ObjectParameter("queId", typeof(string));
    
            var feedbackParameter = feedback != null ?
                new ObjectParameter("feedback", feedback) :
                new ObjectParameter("feedback", typeof(string));
    
            var feedbackTextParameter = feedbackText != null ?
                new ObjectParameter("feedbackText", feedbackText) :
                new ObjectParameter("feedbackText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_insert_mac_widget_feedback", learnerIdParameter, queIdParameter, feedbackParameter, feedbackTextParameter, created);
        }
    
        public virtual ObjectResult<lms_learner_get_course_submodules_Result> lms_learner_get_course_submodules(Nullable<long> courseId, Nullable<long> contactId)
        {
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(long));
    
            var contactIdParameter = contactId.HasValue ?
                new ObjectParameter("contactId", contactId) :
                new ObjectParameter("contactId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_course_submodules_Result>("lms_learner_get_course_submodules", courseIdParameter, contactIdParameter);
        }
    
        public virtual int lms_learner_updateSubModuleProgressRecord(Nullable<long> intContactId, Nullable<long> intSubModuleId)
        {
            var intContactIdParameter = intContactId.HasValue ?
                new ObjectParameter("intContactId", intContactId) :
                new ObjectParameter("intContactId", typeof(long));
    
            var intSubModuleIdParameter = intSubModuleId.HasValue ?
                new ObjectParameter("intSubModuleId", intSubModuleId) :
                new ObjectParameter("intSubModuleId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_updateSubModuleProgressRecord", intContactIdParameter, intSubModuleIdParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_bpc_widget_response_Result> lms_learner_get_bpc_widget_response(string que_guid, Nullable<long> user_id)
        {
            var que_guidParameter = que_guid != null ?
                new ObjectParameter("que_guid", que_guid) :
                new ObjectParameter("que_guid", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_bpc_widget_response_Result>("lms_learner_get_bpc_widget_response", que_guidParameter, user_idParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_RA_attempts_Result> lms_learner_get_RA_attempts(Nullable<long> learner, Nullable<long> ra_id, Nullable<long> subModule_id)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var ra_idParameter = ra_id.HasValue ?
                new ObjectParameter("ra_id", ra_id) :
                new ObjectParameter("ra_id", typeof(long));
    
            var subModule_idParameter = subModule_id.HasValue ?
                new ObjectParameter("subModule_id", subModule_id) :
                new ObjectParameter("subModule_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_RA_attempts_Result>("lms_learner_get_RA_attempts", learnerParameter, ra_idParameter, subModule_idParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_subModule_RAQuestion_Result> lms_learner_get_subModule_RAQuestion(Nullable<long> learner, Nullable<long> intRiskAssessmentResultID, Nullable<long> subModuleId)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var intRiskAssessmentResultIDParameter = intRiskAssessmentResultID.HasValue ?
                new ObjectParameter("intRiskAssessmentResultID", intRiskAssessmentResultID) :
                new ObjectParameter("intRiskAssessmentResultID", typeof(long));
    
            var subModuleIdParameter = subModuleId.HasValue ?
                new ObjectParameter("subModuleId", subModuleId) :
                new ObjectParameter("subModuleId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_subModule_RAQuestion_Result>("lms_learner_get_subModule_RAQuestion", learnerParameter, intRiskAssessmentResultIDParameter, subModuleIdParameter);
        }
    
        public virtual int lms_learner_start_subModuleRiskAssessment(Nullable<long> incontactid, Nullable<long> intRiskAssessmentResultID)
        {
            var incontactidParameter = incontactid.HasValue ?
                new ObjectParameter("incontactid", incontactid) :
                new ObjectParameter("incontactid", typeof(long));
    
            var intRiskAssessmentResultIDParameter = intRiskAssessmentResultID.HasValue ?
                new ObjectParameter("intRiskAssessmentResultID", intRiskAssessmentResultID) :
                new ObjectParameter("intRiskAssessmentResultID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_start_subModuleRiskAssessment", incontactidParameter, intRiskAssessmentResultIDParameter);
        }
    
        public virtual int lms_learner_finish_SubModuleRiskAssessment(Nullable<long> incontactid, Nullable<long> intRiskAssessmentResultID, string strLocationName)
        {
            var incontactidParameter = incontactid.HasValue ?
                new ObjectParameter("incontactid", incontactid) :
                new ObjectParameter("incontactid", typeof(long));
    
            var intRiskAssessmentResultIDParameter = intRiskAssessmentResultID.HasValue ?
                new ObjectParameter("intRiskAssessmentResultID", intRiskAssessmentResultID) :
                new ObjectParameter("intRiskAssessmentResultID", typeof(long));
    
            var strLocationNameParameter = strLocationName != null ?
                new ObjectParameter("strLocationName", strLocationName) :
                new ObjectParameter("strLocationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_learner_finish_SubModuleRiskAssessment", incontactidParameter, intRiskAssessmentResultIDParameter, strLocationNameParameter);
        }
    
        public virtual ObjectResult<lms_learner_get_SubModuleRAResponses_Result> lms_learner_get_SubModuleRAResponses(Nullable<long> learner, Nullable<long> riskAssesmentResultId)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var riskAssesmentResultIdParameter = riskAssesmentResultId.HasValue ?
                new ObjectParameter("riskAssesmentResultId", riskAssesmentResultId) :
                new ObjectParameter("riskAssesmentResultId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_learner_get_SubModuleRAResponses_Result>("lms_learner_get_SubModuleRAResponses", learnerParameter, riskAssesmentResultIdParameter);
        }
    }
}
