//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELG.DAL.DbEntityLearner
{
    using System;
    using System.Collections.Generic;
    
    public partial class lms_widget_details
    {
        public long widgetId { get; set; }
        public string question { get; set; }
        public string response { get; set; }
        public Nullable<System.DateTime> last_updated_on { get; set; }
    }
}
