//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELG.DAL.DbEntityLearner
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCourse
    {
        public int intCourseID { get; set; }
        public string intCourseIdentifier { get; set; }
        public int intOrganisationID { get; set; }
        public string strUnlockKey { get; set; }
        public string strCourse { get; set; }
        public string strCourseSummary { get; set; }
        public string strCourseDescription { get; set; }
        public string strHSContact { get; set; }
        public string strCourseLogo { get; set; }
        public string strCourseTutorialPath { get; set; }
        public string strCourseTestPath { get; set; }
        public bool blnCourseRA { get; set; }
        public Nullable<int> intPassmark { get; set; }
        public Nullable<int> intFrequency { get; set; }
        public Nullable<bool> blnCancelled { get; set; }
        public Nullable<System.DateTime> datModified { get; set; }
        public Nullable<System.DateTime> datCreated { get; set; }
        public int intTestFrequency { get; set; }
        public bool blnTestReminders { get; set; }
        public int intRAFrequency { get; set; }
        public bool blnRAReminder { get; set; }
        public int intTutorialFrequency { get; set; }
        public bool blnTutorialReminder { get; set; }
        public int intTestReminderFreq { get; set; }
        public int intRAReminderFreq { get; set; }
        public int intTutorialReminderFreq { get; set; }
        public int intMaxTestReminders { get; set; }
        public int intMaxRAReminders { get; set; }
        public int intMaxTutorialReminders { get; set; }
        public int intRADaysBefore { get; set; }
        public int intTestDaysBefore { get; set; }
        public int intTutorialDaysBefore { get; set; }
        public bool blnDeptSendRAIssue { get; set; }
        public bool blnDeptSendRAComplete { get; set; }
        public bool blnDeptSendTestPass { get; set; }
        public bool blnDeptSendTestFail { get; set; }
        public bool blnDeptSendRANotCompleted { get; set; }
        public bool blnDeptSendTestNotCompleted { get; set; }
        public bool blnLocSendRAIssue { get; set; }
        public bool blnLocSendRAComplete { get; set; }
        public bool blnLocSendTestPass { get; set; }
        public bool blnLocSendTestFail { get; set; }
        public bool blnLocSendRANotCompleted { get; set; }
        public bool blnLocSendTestNotCompleted { get; set; }
        public bool blnContactSendTest { get; set; }
        public bool blnContactSendRA { get; set; }
        public Nullable<bool> blnCourseActive { get; set; }
        public Nullable<bool> blnHTML5 { get; set; }
        public Nullable<int> intCourseMid { get; set; }
        public string HelpFile { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> isRAModule { get; set; }
        public Nullable<long> intMasterCourseId { get; set; }
        public Nullable<int> intDaysForCompletion { get; set; }
        public Nullable<bool> noLicenceNotification { get; set; }
    }
}
