//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELG.DAL.DbEntityLearner
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrganisationDomainDetail
    {
        public int recordId { get; set; }
        public string domain { get; set; }
        public string css_path { get; set; }
        public string favicon_path { get; set; }
        public Nullable<long> lms_org_id { get; set; }
        public string title_text { get; set; }
        public string logo_path { get; set; }
    }
}
