//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELG.DAL.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContactCourse
    {
        public int intContactID { get; set; }
        public int intCourseID { get; set; }
        public Nullable<int> intRiskAssessmentResultID { get; set; }
        public Nullable<int> intTestResultID { get; set; }
        public Nullable<int> intTutorialResultID { get; set; }
        public bool blnCancelled { get; set; }
        public Nullable<System.DateTime> datCancelled { get; set; }
        public Nullable<System.DateTime> datTestReminderDue { get; set; }
        public Nullable<int> intTestReminderCount { get; set; }
        public Nullable<System.DateTime> datTestCompleted { get; set; }
        public Nullable<System.DateTime> datRAReminderDue { get; set; }
        public Nullable<int> intRAReminderCount { get; set; }
        public Nullable<System.DateTime> datRACompleted { get; set; }
        public Nullable<System.DateTime> datTutorialReminderDue { get; set; }
        public Nullable<int> intTutorialReminderCount { get; set; }
        public Nullable<System.DateTime> datTutorialCompleted { get; set; }
        public Nullable<System.DateTime> datCourseExpiry { get; set; }
        public Nullable<bool> hasStarted { get; set; }
    }
}
