//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELG.DAL.DBEntitySA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Microsoft.Extensions.Configuration;
    
    public partial class superadmindbEntities : DbContext
    {
        public static IConfiguration _configuration { get; set; }

        public superadmindbEntities()
            : base(GetConnectionString())
        {
        }

        private static string GetConnectionString()
        {
            if (_configuration != null)
            {
                var connStr = _configuration.GetConnectionString("superadmindbEntities");
                if (!string.IsNullOrEmpty(connStr))
                {
                    return connStr;
                }
            }

            return "name=superadmindbEntities";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<lms_super_admin_getSuspendDataRecords_Result> lms_super_admin_getSuspendDataRecords(Nullable<long> intContactId)
        {
            var intContactIdParameter = intContactId.HasValue ?
                new ObjectParameter("intContactId", intContactId) :
                new ObjectParameter("intContactId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_super_admin_getSuspendDataRecords_Result>("lms_super_admin_getSuspendDataRecords", intContactIdParameter);
        }
    
        public virtual int lms_superadmin_assign_company_licence(Nullable<long> comany, Nullable<long> course, Nullable<int> addedLicences, Nullable<int> revokedLicences, ObjectParameter retval)
        {
            var comanyParameter = comany.HasValue ?
                new ObjectParameter("comany", comany) :
                new ObjectParameter("comany", typeof(long));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            var addedLicencesParameter = addedLicences.HasValue ?
                new ObjectParameter("addedLicences", addedLicences) :
                new ObjectParameter("addedLicences", typeof(int));
    
            var revokedLicencesParameter = revokedLicences.HasValue ?
                new ObjectParameter("revokedLicences", revokedLicences) :
                new ObjectParameter("revokedLicences", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_assign_company_licence", comanyParameter, courseParameter, addedLicencesParameter, revokedLicencesParameter, retval);
        }
    
        public virtual int lms_superadmin_assign_company_new_licence(string organisation, Nullable<long> course, Nullable<int> addedLicences, Nullable<int> revokedLicences, ObjectParameter retval)
        {
            var organisationParameter = organisation != null ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(string));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            var addedLicencesParameter = addedLicences.HasValue ?
                new ObjectParameter("addedLicences", addedLicences) :
                new ObjectParameter("addedLicences", typeof(int));
    
            var revokedLicencesParameter = revokedLicences.HasValue ?
                new ObjectParameter("revokedLicences", revokedLicences) :
                new ObjectParameter("revokedLicences", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_assign_company_new_licence", organisationParameter, courseParameter, addedLicencesParameter, revokedLicencesParameter, retval);
        }
    
        public virtual int lms_superadmin_assign_course_to_company(Nullable<long> intOrganisationid, Nullable<long> intCourseId, ObjectParameter intRetCourseId)
        {
            var intOrganisationidParameter = intOrganisationid.HasValue ?
                new ObjectParameter("intOrganisationid", intOrganisationid) :
                new ObjectParameter("intOrganisationid", typeof(long));
    
            var intCourseIdParameter = intCourseId.HasValue ?
                new ObjectParameter("intCourseId", intCourseId) :
                new ObjectParameter("intCourseId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_assign_course_to_company", intOrganisationidParameter, intCourseIdParameter, intRetCourseId);
        }
    
        public virtual int lms_superadmin_assign_new_course_to_company(string organisation, Nullable<long> intCourseId, ObjectParameter intRetCourseId)
        {
            var organisationParameter = organisation != null ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(string));
    
            var intCourseIdParameter = intCourseId.HasValue ?
                new ObjectParameter("intCourseId", intCourseId) :
                new ObjectParameter("intCourseId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_assign_new_course_to_company", organisationParameter, intCourseIdParameter, intRetCourseId);
        }
    
        public virtual int lms_superadmin_create_CompanyAdminLearner(string title, string firstname, string lastname, string email, string organisation, Nullable<long> location, Nullable<long> department, ObjectParameter id)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var organisationParameter = organisation != null ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(string));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(long));
    
            var departmentParameter = department.HasValue ?
                new ObjectParameter("department", department) :
                new ObjectParameter("department", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_CompanyAdminLearner", titleParameter, firstnameParameter, lastnameParameter, emailParameter, organisationParameter, locationParameter, departmentParameter, id);
        }
    
        public virtual int lms_superadmin_create_deleted_company_record(Nullable<long> adminid, Nullable<long> orgid, string orgName, string orgNumber, ObjectParameter retVal)
        {
            var adminidParameter = adminid.HasValue ?
                new ObjectParameter("adminid", adminid) :
                new ObjectParameter("adminid", typeof(long));
    
            var orgidParameter = orgid.HasValue ?
                new ObjectParameter("orgid", orgid) :
                new ObjectParameter("orgid", typeof(long));
    
            var orgNameParameter = orgName != null ?
                new ObjectParameter("orgName", orgName) :
                new ObjectParameter("orgName", typeof(string));
    
            var orgNumberParameter = orgNumber != null ?
                new ObjectParameter("orgNumber", orgNumber) :
                new ObjectParameter("orgNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_deleted_company_record", adminidParameter, orgidParameter, orgNameParameter, orgNumberParameter, retVal);
        }
    
        public virtual int lms_superadmin_create_department(string organisation, string departmentName, ObjectParameter newDepId)
        {
            var organisationParameter = organisation != null ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(string));
    
            var departmentNameParameter = departmentName != null ?
                new ObjectParameter("departmentName", departmentName) :
                new ObjectParameter("departmentName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_department", organisationParameter, departmentNameParameter, newDepId);
        }
    
        public virtual int lms_superadmin_create_location(string organisation, string locationName, ObjectParameter newLocId)
        {
            var organisationParameter = organisation != null ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(string));
    
            var locationNameParameter = locationName != null ?
                new ObjectParameter("locationName", locationName) :
                new ObjectParameter("locationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_location", organisationParameter, locationNameParameter, newLocId);
        }
    
        public virtual int lms_superadmin_create_location_department(string organisation, Nullable<long> location, string departmentName, ObjectParameter newDepId)
        {
            var organisationParameter = organisation != null ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(string));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(long));
    
            var departmentNameParameter = departmentName != null ?
                new ObjectParameter("departmentName", departmentName) :
                new ObjectParameter("departmentName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_location_department", organisationParameter, locationParameter, departmentNameParameter, newDepId);
        }
    
        public virtual int lms_superadmin_create_NewRiskAssessment(string title, string summary, string description, ObjectParameter id)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var summaryParameter = summary != null ?
                new ObjectParameter("summary", summary) :
                new ObjectParameter("summary", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_NewRiskAssessment", titleParameter, summaryParameter, descriptionParameter, id);
        }
    
        public virtual int lms_superadmin_create_NewRiskAssessmentGroup(string groupName, Nullable<long> raid, ObjectParameter id)
        {
            var groupNameParameter = groupName != null ?
                new ObjectParameter("groupName", groupName) :
                new ObjectParameter("groupName", typeof(string));
    
            var raidParameter = raid.HasValue ?
                new ObjectParameter("raid", raid) :
                new ObjectParameter("raid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_NewRiskAssessmentGroup", groupNameParameter, raidParameter, id);
        }
    
        public virtual int lms_superadmin_create_organisation(Nullable<long> reseller, string organisationName, string orgBrandName, string contractManagerName, string contractManagerEmail, string supportEmail, string supportPhone, string orgBaseURL, string expiryDate, string sector, string rate, string owner, string trainingManagerFirstName, string trainingManagerLastName, string trainingManagerEmail, string trainingManagerPhone, string trainingManagerExtension, string sequentialId, Nullable<bool> isReseller, Nullable<int> maxAllowedUserCount, ObjectParameter id)
        {
            var resellerParameter = reseller.HasValue ?
                new ObjectParameter("reseller", reseller) :
                new ObjectParameter("reseller", typeof(long));
    
            var organisationNameParameter = organisationName != null ?
                new ObjectParameter("organisationName", organisationName) :
                new ObjectParameter("organisationName", typeof(string));
    
            var orgBrandNameParameter = orgBrandName != null ?
                new ObjectParameter("orgBrandName", orgBrandName) :
                new ObjectParameter("orgBrandName", typeof(string));
    
            var contractManagerNameParameter = contractManagerName != null ?
                new ObjectParameter("contractManagerName", contractManagerName) :
                new ObjectParameter("contractManagerName", typeof(string));
    
            var contractManagerEmailParameter = contractManagerEmail != null ?
                new ObjectParameter("contractManagerEmail", contractManagerEmail) :
                new ObjectParameter("contractManagerEmail", typeof(string));
    
            var supportEmailParameter = supportEmail != null ?
                new ObjectParameter("supportEmail", supportEmail) :
                new ObjectParameter("supportEmail", typeof(string));
    
            var supportPhoneParameter = supportPhone != null ?
                new ObjectParameter("supportPhone", supportPhone) :
                new ObjectParameter("supportPhone", typeof(string));
    
            var orgBaseURLParameter = orgBaseURL != null ?
                new ObjectParameter("orgBaseURL", orgBaseURL) :
                new ObjectParameter("orgBaseURL", typeof(string));
    
            var expiryDateParameter = expiryDate != null ?
                new ObjectParameter("expiryDate", expiryDate) :
                new ObjectParameter("expiryDate", typeof(string));
    
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var rateParameter = rate != null ?
                new ObjectParameter("rate", rate) :
                new ObjectParameter("rate", typeof(string));
    
            var ownerParameter = owner != null ?
                new ObjectParameter("owner", owner) :
                new ObjectParameter("owner", typeof(string));
    
            var trainingManagerFirstNameParameter = trainingManagerFirstName != null ?
                new ObjectParameter("trainingManagerFirstName", trainingManagerFirstName) :
                new ObjectParameter("trainingManagerFirstName", typeof(string));
    
            var trainingManagerLastNameParameter = trainingManagerLastName != null ?
                new ObjectParameter("trainingManagerLastName", trainingManagerLastName) :
                new ObjectParameter("trainingManagerLastName", typeof(string));
    
            var trainingManagerEmailParameter = trainingManagerEmail != null ?
                new ObjectParameter("trainingManagerEmail", trainingManagerEmail) :
                new ObjectParameter("trainingManagerEmail", typeof(string));
    
            var trainingManagerPhoneParameter = trainingManagerPhone != null ?
                new ObjectParameter("trainingManagerPhone", trainingManagerPhone) :
                new ObjectParameter("trainingManagerPhone", typeof(string));
    
            var trainingManagerExtensionParameter = trainingManagerExtension != null ?
                new ObjectParameter("trainingManagerExtension", trainingManagerExtension) :
                new ObjectParameter("trainingManagerExtension", typeof(string));
    
            var sequentialIdParameter = sequentialId != null ?
                new ObjectParameter("sequentialId", sequentialId) :
                new ObjectParameter("sequentialId", typeof(string));
    
            var isResellerParameter = isReseller.HasValue ?
                new ObjectParameter("isReseller", isReseller) :
                new ObjectParameter("isReseller", typeof(bool));
    
            var maxAllowedUserCountParameter = maxAllowedUserCount.HasValue ?
                new ObjectParameter("maxAllowedUserCount", maxAllowedUserCount) :
                new ObjectParameter("maxAllowedUserCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_organisation", resellerParameter, organisationNameParameter, orgBrandNameParameter, contractManagerNameParameter, contractManagerEmailParameter, supportEmailParameter, supportPhoneParameter, orgBaseURLParameter, expiryDateParameter, sectorParameter, rateParameter, ownerParameter, trainingManagerFirstNameParameter, trainingManagerLastNameParameter, trainingManagerEmailParameter, trainingManagerPhoneParameter, trainingManagerExtensionParameter, sequentialIdParameter, isResellerParameter, maxAllowedUserCountParameter, id);
        }
    
        public virtual int lms_superadmin_create_ra_ques_to_company(Nullable<long> masterCourseId, Nullable<long> intCourseId)
        {
            var masterCourseIdParameter = masterCourseId.HasValue ?
                new ObjectParameter("masterCourseId", masterCourseId) :
                new ObjectParameter("masterCourseId", typeof(long));
    
            var intCourseIdParameter = intCourseId.HasValue ?
                new ObjectParameter("intCourseId", intCourseId) :
                new ObjectParameter("intCourseId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_ra_ques_to_company", masterCourseIdParameter, intCourseIdParameter);
        }
    
        public virtual int lms_superadmin_create_RAQue(string question, string additionalText, Nullable<long> group, string groupText, Nullable<long> course, ObjectParameter id)
        {
            var questionParameter = question != null ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(string));
    
            var additionalTextParameter = additionalText != null ?
                new ObjectParameter("additionalText", additionalText) :
                new ObjectParameter("additionalText", typeof(string));
    
            var groupParameter = group.HasValue ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(long));
    
            var groupTextParameter = groupText != null ?
                new ObjectParameter("groupText", groupText) :
                new ObjectParameter("groupText", typeof(string));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_RAQue", questionParameter, additionalTextParameter, groupParameter, groupTextParameter, courseParameter, id);
        }
    
        public virtual int lms_superadmin_create_RAQueOption(string option, Nullable<long> question, Nullable<int> order, Nullable<bool> issue, ObjectParameter id)
        {
            var optionParameter = option != null ?
                new ObjectParameter("option", option) :
                new ObjectParameter("option", typeof(string));
    
            var questionParameter = question.HasValue ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(long));
    
            var orderParameter = order.HasValue ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(int));
    
            var issueParameter = issue.HasValue ?
                new ObjectParameter("issue", issue) :
                new ObjectParameter("issue", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_RAQueOption", optionParameter, questionParameter, orderParameter, issueParameter, id);
        }
    
        public virtual int lms_superadmin_delete_company(Nullable<long> orgId, Nullable<long> adminid, string otp, ObjectParameter retVal)
        {
            var orgIdParameter = orgId.HasValue ?
                new ObjectParameter("OrgId", orgId) :
                new ObjectParameter("OrgId", typeof(long));
    
            var adminidParameter = adminid.HasValue ?
                new ObjectParameter("adminid", adminid) :
                new ObjectParameter("adminid", typeof(long));
    
            var otpParameter = otp != null ?
                new ObjectParameter("otp", otp) :
                new ObjectParameter("otp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_delete_company", orgIdParameter, adminidParameter, otpParameter, retVal);
        }
    
        public virtual int lms_superadmin_delete_department(Nullable<long> depId, ObjectParameter retVal)
        {
            var depIdParameter = depId.HasValue ?
                new ObjectParameter("DepId", depId) :
                new ObjectParameter("DepId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_delete_department", depIdParameter, retVal);
        }
    
        public virtual int lms_superadmin_delete_RAQuestion(Nullable<long> question, ObjectParameter id)
        {
            var questionParameter = question.HasValue ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_delete_RAQuestion", questionParameter, id);
        }
    
        public virtual int lms_superadmin_delete_RAQuestionOption(Nullable<long> optionid, ObjectParameter id)
        {
            var optionidParameter = optionid.HasValue ?
                new ObjectParameter("optionid", optionid) :
                new ObjectParameter("optionid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_delete_RAQuestionOption", optionidParameter, id);
        }
    
        public virtual int lms_superadmin_delete_reseller(Nullable<long> orgId, Nullable<long> adminid, string otp, ObjectParameter retVal)
        {
            var orgIdParameter = orgId.HasValue ?
                new ObjectParameter("OrgId", orgId) :
                new ObjectParameter("OrgId", typeof(long));
    
            var adminidParameter = adminid.HasValue ?
                new ObjectParameter("adminid", adminid) :
                new ObjectParameter("adminid", typeof(long));
    
            var otpParameter = otp != null ?
                new ObjectParameter("otp", otp) :
                new ObjectParameter("otp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_delete_reseller", orgIdParameter, adminidParameter, otpParameter, retVal);
        }
    
        public virtual ObjectResult<lms_superadmin_get_AboutToExpiryCompanies_ThisWeek_Result> lms_superadmin_get_AboutToExpiryCompanies_ThisWeek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_AboutToExpiryCompanies_ThisWeek_Result>("lms_superadmin_get_AboutToExpiryCompanies_ThisWeek");
        }
    
        public virtual ObjectResult<lms_superadmin_get_AllDepartmentsForLocation_Result> lms_superadmin_get_AllDepartmentsForLocation(Nullable<long> location)
        {
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_AllDepartmentsForLocation_Result>("lms_superadmin_get_AllDepartmentsForLocation", locationParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_AllOptionsForQuestion_Result> lms_superadmin_get_AllOptionsForQuestion(Nullable<long> question)
        {
            var questionParameter = question.HasValue ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_AllOptionsForQuestion_Result>("lms_superadmin_get_AllOptionsForQuestion", questionParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_AllResellers_Result> lms_superadmin_get_AllResellers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_AllResellers_Result>("lms_superadmin_get_AllResellers");
        }
    
        public virtual ObjectResult<lms_superadmin_get_certificate_record_Result> lms_superadmin_get_certificate_record(Nullable<long> recordid)
        {
            var recordidParameter = recordid.HasValue ?
                new ObjectParameter("recordid", recordid) :
                new ObjectParameter("recordid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_certificate_record_Result>("lms_superadmin_get_certificate_record", recordidParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_company_course_licences_Result> lms_superadmin_get_company_course_licences(string comany, string search, string sortCol, string sortDir)
        {
            var comanyParameter = comany != null ?
                new ObjectParameter("comany", comany) :
                new ObjectParameter("comany", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_company_course_licences_Result>("lms_superadmin_get_company_course_licences", comanyParameter, searchParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_CompanyAdminList_Result> lms_superadmin_get_CompanyAdminList(string organisation, string learnerName, string sortCol, string sortDir)
        {
            var organisationParameter = organisation != null ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(string));
    
            var learnerNameParameter = learnerName != null ?
                new ObjectParameter("learnerName", learnerName) :
                new ObjectParameter("learnerName", typeof(string));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_CompanyAdminList_Result>("lms_superadmin_get_CompanyAdminList", organisationParameter, learnerNameParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<byte[]> lms_superadmin_get_companyCertificate(string orgUID)
        {
            var orgUIDParameter = orgUID != null ?
                new ObjectParameter("orgUID", orgUID) :
                new ObjectParameter("orgUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("lms_superadmin_get_companyCertificate", orgUIDParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_companyInfo_Result> lms_superadmin_get_companyInfo(string orgUID)
        {
            var orgUIDParameter = orgUID != null ?
                new ObjectParameter("orgUID", orgUID) :
                new ObjectParameter("orgUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_companyInfo_Result>("lms_superadmin_get_companyInfo", orgUIDParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_companyListing_Result> lms_superadmin_get_companyListing(Nullable<long> resller, string companyName, string companySector, string companyOwner, Nullable<int> status, string sortCol, string sortDir)
        {
            var resllerParameter = resller.HasValue ?
                new ObjectParameter("resller", resller) :
                new ObjectParameter("resller", typeof(long));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var companySectorParameter = companySector != null ?
                new ObjectParameter("companySector", companySector) :
                new ObjectParameter("companySector", typeof(string));
    
            var companyOwnerParameter = companyOwner != null ?
                new ObjectParameter("companyOwner", companyOwner) :
                new ObjectParameter("companyOwner", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_companyListing_Result>("lms_superadmin_get_companyListing", resllerParameter, companyNameParameter, companySectorParameter, companyOwnerParameter, statusParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_companyListing_assigned_course_Result> lms_superadmin_get_companyListing_assigned_course(Nullable<long> course, string companyName, Nullable<int> status, string sortCol, string sortDir)
        {
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_companyListing_assigned_course_Result>("lms_superadmin_get_companyListing_assigned_course", courseParameter, companyNameParameter, statusParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_companyListing_dropoff_Result> lms_superadmin_get_companyListing_dropoff(Nullable<long> resller, string companyName, Nullable<int> status, string sortCol, string sortDir)
        {
            var resllerParameter = resller.HasValue ?
                new ObjectParameter("resller", resller) :
                new ObjectParameter("resller", typeof(long));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_companyListing_dropoff_Result>("lms_superadmin_get_companyListing_dropoff", resllerParameter, companyNameParameter, statusParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_CourseInfo_Result> lms_superadmin_get_CourseInfo(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_CourseInfo_Result>("lms_superadmin_get_CourseInfo", idParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_crm_companyListing_Result> lms_superadmin_get_crm_companyListing(string filter, string sortCol, string sortDir)
        {
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_crm_companyListing_Result>("lms_superadmin_get_crm_companyListing", filterParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_dash_WeeklyProgress_Result> lms_superadmin_get_dash_WeeklyProgress()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_dash_WeeklyProgress_Result>("lms_superadmin_get_dash_WeeklyProgress");
        }
    
        public virtual ObjectResult<lms_superadmin_get_dash_YearlyCompletion_Result> lms_superadmin_get_dash_YearlyCompletion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_dash_YearlyCompletion_Result>("lms_superadmin_get_dash_YearlyCompletion");
        }
    
        public virtual ObjectResult<lms_superadmin_get_LearnerCourseLauchDetails_Result> lms_superadmin_get_LearnerCourseLauchDetails(Nullable<long> intContactId, Nullable<long> intCourse, string sortCol, string sortDir)
        {
            var intContactIdParameter = intContactId.HasValue ?
                new ObjectParameter("intContactId", intContactId) :
                new ObjectParameter("intContactId", typeof(long));
    
            var intCourseParameter = intCourse.HasValue ?
                new ObjectParameter("intCourse", intCourse) :
                new ObjectParameter("intCourse", typeof(long));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_LearnerCourseLauchDetails_Result>("lms_superadmin_get_LearnerCourseLauchDetails", intContactIdParameter, intCourseParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_LearnerProgressReport_Result> lms_superadmin_get_LearnerProgressReport(string learnerName, string companyName, string status, Nullable<long> course, string sortCol, string sortDir, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var learnerNameParameter = learnerName != null ?
                new ObjectParameter("learnerName", learnerName) :
                new ObjectParameter("learnerName", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_LearnerProgressReport_Result>("lms_superadmin_get_LearnerProgressReport", learnerNameParameter, companyNameParameter, statusParameter, courseParameter, sortColParameter, sortDirParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_moduleListing_Result> lms_superadmin_get_moduleListing(string moduleName, Nullable<int> status, string sortCol, string sortDir)
        {
            var moduleNameParameter = moduleName != null ?
                new ObjectParameter("moduleName", moduleName) :
                new ObjectParameter("moduleName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_moduleListing_Result>("lms_superadmin_get_moduleListing", moduleNameParameter, statusParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<string> lms_superadmin_get_OTP(Nullable<long> adminid)
        {
            var adminidParameter = adminid.HasValue ?
                new ObjectParameter("adminid", adminid) :
                new ObjectParameter("adminid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("lms_superadmin_get_OTP", adminidParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_RAQuestionInfo_Result> lms_superadmin_get_RAQuestionInfo(Nullable<long> question)
        {
            var questionParameter = question.HasValue ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_RAQuestionInfo_Result>("lms_superadmin_get_RAQuestionInfo", questionParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_RegisteredLearners_Result> lms_superadmin_get_RegisteredLearners(string learnerName, string organisationName, Nullable<int> status, string sortCol, string sortDir)
        {
            var learnerNameParameter = learnerName != null ?
                new ObjectParameter("learnerName", learnerName) :
                new ObjectParameter("learnerName", typeof(string));
    
            var organisationNameParameter = organisationName != null ?
                new ObjectParameter("organisationName", organisationName) :
                new ObjectParameter("organisationName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_RegisteredLearners_Result>("lms_superadmin_get_RegisteredLearners", learnerNameParameter, organisationNameParameter, statusParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_resellerListing_Result> lms_superadmin_get_resellerListing(string companyName, Nullable<int> status, string sortCol, string sortDir)
        {
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_resellerListing_Result>("lms_superadmin_get_resellerListing", companyNameParameter, statusParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_RiskAssessmentAnswerSheet_Result> lms_superadmin_get_RiskAssessmentAnswerSheet(Nullable<long> raid)
        {
            var raidParameter = raid.HasValue ?
                new ObjectParameter("raid", raid) :
                new ObjectParameter("raid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_RiskAssessmentAnswerSheet_Result>("lms_superadmin_get_RiskAssessmentAnswerSheet", raidParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_getAdminLoginDetails_Result> lms_superadmin_getAdminLoginDetails(string useremail, string pwd, Nullable<bool> masterPwd)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var masterPwdParameter = masterPwd.HasValue ?
                new ObjectParameter("masterPwd", masterPwd) :
                new ObjectParameter("masterPwd", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_getAdminLoginDetails_Result>("lms_superadmin_getAdminLoginDetails", useremailParameter, pwdParameter, masterPwdParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_getAllCompnayDepartments_Result> lms_superadmin_getAllCompnayDepartments(string company, string search)
        {
            var companyParameter = company != null ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_getAllCompnayDepartments_Result>("lms_superadmin_getAllCompnayDepartments", companyParameter, searchParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_getAllCompnayLocations_Result> lms_superadmin_getAllCompnayLocations(string company, string search)
        {
            var companyParameter = company != null ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_getAllCompnayLocations_Result>("lms_superadmin_getAllCompnayLocations", companyParameter, searchParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_getCourseLauchDetails_Result> lms_superadmin_getCourseLauchDetails(Nullable<long> intContactId, string sortCol, string sortDir)
        {
            var intContactIdParameter = intContactId.HasValue ?
                new ObjectParameter("intContactId", intContactId) :
                new ObjectParameter("intContactId", typeof(long));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_getCourseLauchDetails_Result>("lms_superadmin_getCourseLauchDetails", intContactIdParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_getLearnerLoginDetails_Result> lms_superadmin_getLearnerLoginDetails(Nullable<long> intContactId, string sortCol, string sortDir)
        {
            var intContactIdParameter = intContactId.HasValue ?
                new ObjectParameter("intContactId", intContactId) :
                new ObjectParameter("intContactId", typeof(long));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_getLearnerLoginDetails_Result>("lms_superadmin_getLearnerLoginDetails", intContactIdParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual int lms_superadmin_insert_companyBanner(string orgUID, byte[] banner, ObjectParameter update)
        {
            var orgUIDParameter = orgUID != null ?
                new ObjectParameter("orgUID", orgUID) :
                new ObjectParameter("orgUID", typeof(string));
    
            var bannerParameter = banner != null ?
                new ObjectParameter("banner", banner) :
                new ObjectParameter("banner", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_insert_companyBanner", orgUIDParameter, bannerParameter, update);
        }
    
        public virtual int lms_superadmin_insert_companyCertificate(string orgUID, byte[] certificate, ObjectParameter update)
        {
            var orgUIDParameter = orgUID != null ?
                new ObjectParameter("orgUID", orgUID) :
                new ObjectParameter("orgUID", typeof(string));
    
            var certificateParameter = certificate != null ?
                new ObjectParameter("certificate", certificate) :
                new ObjectParameter("certificate", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_insert_companyCertificate", orgUIDParameter, certificateParameter, update);
        }
    
        public virtual int lms_superadmin_insert_LocDepMap(Nullable<long> locId, Nullable<long> depId, ObjectParameter retVal)
        {
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("locId", locId) :
                new ObjectParameter("locId", typeof(long));
    
            var depIdParameter = depId.HasValue ?
                new ObjectParameter("depId", depId) :
                new ObjectParameter("depId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_insert_LocDepMap", locIdParameter, depIdParameter, retVal);
        }
    
        public virtual int lms_superadmin_refresh_module_assignment(Nullable<long> course, ObjectParameter retval)
        {
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_refresh_module_assignment", courseParameter, retval);
        }
    
        public virtual int lms_superadmin_remove_customcertificate(string org_guid, ObjectParameter retVal)
        {
            var org_guidParameter = org_guid != null ?
                new ObjectParameter("org_guid", org_guid) :
                new ObjectParameter("org_guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_remove_customcertificate", org_guidParameter, retVal);
        }
    
        public virtual int lms_superadmin_remove_customlogo(string org_guid, ObjectParameter retVal)
        {
            var org_guidParameter = org_guid != null ?
                new ObjectParameter("org_guid", org_guid) :
                new ObjectParameter("org_guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_remove_customlogo", org_guidParameter, retVal);
        }
    
        public virtual int lms_superadmin_remove_superadmin_rights(Nullable<long> userId, ObjectParameter retVal)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_remove_superadmin_rights", userIdParameter, retVal);
        }
    
        public virtual int lms_superadmin_Reset_LearnerPassword(Nullable<long> intContactID, string pwd)
        {
            var intContactIDParameter = intContactID.HasValue ?
                new ObjectParameter("intContactID", intContactID) :
                new ObjectParameter("intContactID", typeof(long));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_Reset_LearnerPassword", intContactIDParameter, pwdParameter);
        }
    
        public virtual int lms_superadmin_update_CompanyActiveStatus(string org_guid, Nullable<bool> status, ObjectParameter retVal)
        {
            var org_guidParameter = org_guid != null ?
                new ObjectParameter("org_guid", org_guid) :
                new ObjectParameter("org_guid", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_CompanyActiveStatus", org_guidParameter, statusParameter, retVal);
        }
    
        public virtual int lms_superadmin_update_CompanyFieldTextSettings(string titleDescription, string firstNameDescription, string lastNameDescription, string emailDescription, string locationDescription, string departmentDescription, string org_guid, ObjectParameter retVal)
        {
            var titleDescriptionParameter = titleDescription != null ?
                new ObjectParameter("TitleDescription", titleDescription) :
                new ObjectParameter("TitleDescription", typeof(string));
    
            var firstNameDescriptionParameter = firstNameDescription != null ?
                new ObjectParameter("FirstNameDescription", firstNameDescription) :
                new ObjectParameter("FirstNameDescription", typeof(string));
    
            var lastNameDescriptionParameter = lastNameDescription != null ?
                new ObjectParameter("LastNameDescription", lastNameDescription) :
                new ObjectParameter("LastNameDescription", typeof(string));
    
            var emailDescriptionParameter = emailDescription != null ?
                new ObjectParameter("EmailDescription", emailDescription) :
                new ObjectParameter("EmailDescription", typeof(string));
    
            var locationDescriptionParameter = locationDescription != null ?
                new ObjectParameter("LocationDescription", locationDescription) :
                new ObjectParameter("LocationDescription", typeof(string));
    
            var departmentDescriptionParameter = departmentDescription != null ?
                new ObjectParameter("DepartmentDescription", departmentDescription) :
                new ObjectParameter("DepartmentDescription", typeof(string));
    
            var org_guidParameter = org_guid != null ?
                new ObjectParameter("org_guid", org_guid) :
                new ObjectParameter("org_guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_CompanyFieldTextSettings", titleDescriptionParameter, firstNameDescriptionParameter, lastNameDescriptionParameter, emailDescriptionParameter, locationDescriptionParameter, departmentDescriptionParameter, org_guidParameter, retVal);
        }
    
        public virtual int lms_superadmin_update_CompanyGeneralSettings(Nullable<bool> docEnable, Nullable<int> allowedUploadCount, Nullable<int> allowedAccidentIncidentFeature, Nullable<int> trainingRenewalMode, Nullable<int> courseAssignMode, Nullable<bool> selfRegistration, string org_guid, ObjectParameter retVal)
        {
            var docEnableParameter = docEnable.HasValue ?
                new ObjectParameter("docEnable", docEnable) :
                new ObjectParameter("docEnable", typeof(bool));
    
            var allowedUploadCountParameter = allowedUploadCount.HasValue ?
                new ObjectParameter("allowedUploadCount", allowedUploadCount) :
                new ObjectParameter("allowedUploadCount", typeof(int));
    
            var allowedAccidentIncidentFeatureParameter = allowedAccidentIncidentFeature.HasValue ?
                new ObjectParameter("allowedAccidentIncidentFeature", allowedAccidentIncidentFeature) :
                new ObjectParameter("allowedAccidentIncidentFeature", typeof(int));
    
            var trainingRenewalModeParameter = trainingRenewalMode.HasValue ?
                new ObjectParameter("trainingRenewalMode", trainingRenewalMode) :
                new ObjectParameter("trainingRenewalMode", typeof(int));
    
            var courseAssignModeParameter = courseAssignMode.HasValue ?
                new ObjectParameter("courseAssignMode", courseAssignMode) :
                new ObjectParameter("courseAssignMode", typeof(int));
    
            var selfRegistrationParameter = selfRegistration.HasValue ?
                new ObjectParameter("selfRegistration", selfRegistration) :
                new ObjectParameter("selfRegistration", typeof(bool));
    
            var org_guidParameter = org_guid != null ?
                new ObjectParameter("org_guid", org_guid) :
                new ObjectParameter("org_guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_CompanyGeneralSettings", docEnableParameter, allowedUploadCountParameter, allowedAccidentIncidentFeatureParameter, trainingRenewalModeParameter, courseAssignModeParameter, selfRegistrationParameter, org_guidParameter, retVal);
        }
    
        public virtual int lms_superadmin_update_CompanyInformation(Nullable<long> reseller, string organisationName, string orgBrandName, string contractManagerName, string contractManagerEmail, string supportEmail, string supportPhone, string orgBaseURL, string expiryDate, string sector, string rate, string trainingManagerFirstName, string trainingManagerLastName, string trainingManagerEmail, string trainingManagerPhone, string trainingManagerExtension, string companyOwner, string org_guid, Nullable<int> maxAllowedUserCount, ObjectParameter retVal)
        {
            var resellerParameter = reseller.HasValue ?
                new ObjectParameter("reseller", reseller) :
                new ObjectParameter("reseller", typeof(long));
    
            var organisationNameParameter = organisationName != null ?
                new ObjectParameter("organisationName", organisationName) :
                new ObjectParameter("organisationName", typeof(string));
    
            var orgBrandNameParameter = orgBrandName != null ?
                new ObjectParameter("orgBrandName", orgBrandName) :
                new ObjectParameter("orgBrandName", typeof(string));
    
            var contractManagerNameParameter = contractManagerName != null ?
                new ObjectParameter("contractManagerName", contractManagerName) :
                new ObjectParameter("contractManagerName", typeof(string));
    
            var contractManagerEmailParameter = contractManagerEmail != null ?
                new ObjectParameter("contractManagerEmail", contractManagerEmail) :
                new ObjectParameter("contractManagerEmail", typeof(string));
    
            var supportEmailParameter = supportEmail != null ?
                new ObjectParameter("supportEmail", supportEmail) :
                new ObjectParameter("supportEmail", typeof(string));
    
            var supportPhoneParameter = supportPhone != null ?
                new ObjectParameter("supportPhone", supportPhone) :
                new ObjectParameter("supportPhone", typeof(string));
    
            var orgBaseURLParameter = orgBaseURL != null ?
                new ObjectParameter("orgBaseURL", orgBaseURL) :
                new ObjectParameter("orgBaseURL", typeof(string));
    
            var expiryDateParameter = expiryDate != null ?
                new ObjectParameter("expiryDate", expiryDate) :
                new ObjectParameter("expiryDate", typeof(string));
    
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var rateParameter = rate != null ?
                new ObjectParameter("rate", rate) :
                new ObjectParameter("rate", typeof(string));
    
            var trainingManagerFirstNameParameter = trainingManagerFirstName != null ?
                new ObjectParameter("trainingManagerFirstName", trainingManagerFirstName) :
                new ObjectParameter("trainingManagerFirstName", typeof(string));
    
            var trainingManagerLastNameParameter = trainingManagerLastName != null ?
                new ObjectParameter("trainingManagerLastName", trainingManagerLastName) :
                new ObjectParameter("trainingManagerLastName", typeof(string));
    
            var trainingManagerEmailParameter = trainingManagerEmail != null ?
                new ObjectParameter("trainingManagerEmail", trainingManagerEmail) :
                new ObjectParameter("trainingManagerEmail", typeof(string));
    
            var trainingManagerPhoneParameter = trainingManagerPhone != null ?
                new ObjectParameter("trainingManagerPhone", trainingManagerPhone) :
                new ObjectParameter("trainingManagerPhone", typeof(string));
    
            var trainingManagerExtensionParameter = trainingManagerExtension != null ?
                new ObjectParameter("trainingManagerExtension", trainingManagerExtension) :
                new ObjectParameter("trainingManagerExtension", typeof(string));
    
            var companyOwnerParameter = companyOwner != null ?
                new ObjectParameter("companyOwner", companyOwner) :
                new ObjectParameter("companyOwner", typeof(string));
    
            var org_guidParameter = org_guid != null ?
                new ObjectParameter("org_guid", org_guid) :
                new ObjectParameter("org_guid", typeof(string));
    
            var maxAllowedUserCountParameter = maxAllowedUserCount.HasValue ?
                new ObjectParameter("maxAllowedUserCount", maxAllowedUserCount) :
                new ObjectParameter("maxAllowedUserCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_CompanyInformation", resellerParameter, organisationNameParameter, orgBrandNameParameter, contractManagerNameParameter, contractManagerEmailParameter, supportEmailParameter, supportPhoneParameter, orgBaseURLParameter, expiryDateParameter, sectorParameter, rateParameter, trainingManagerFirstNameParameter, trainingManagerLastNameParameter, trainingManagerEmailParameter, trainingManagerPhoneParameter, trainingManagerExtensionParameter, companyOwnerParameter, org_guidParameter, maxAllowedUserCountParameter, retVal);
        }
    
        public virtual int lms_superadmin_update_CompanyModuleAccess(Nullable<long> course, Nullable<bool> status, ObjectParameter retval)
        {
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_CompanyModuleAccess", courseParameter, statusParameter, retval);
        }
    
        public virtual int lms_superadmin_update_CompanyNotes(string notes, string org_guid, ObjectParameter retVal)
        {
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            var org_guidParameter = org_guid != null ?
                new ObjectParameter("org_guid", org_guid) :
                new ObjectParameter("org_guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_CompanyNotes", notesParameter, org_guidParameter, retVal);
        }
    
        public virtual int lms_superadmin_update_CourseInfo(Nullable<long> courseid, string title, string summary, string description, ObjectParameter retval)
        {
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(long));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var summaryParameter = summary != null ?
                new ObjectParameter("summary", summary) :
                new ObjectParameter("summary", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_CourseInfo", courseidParameter, titleParameter, summaryParameter, descriptionParameter, retval);
        }
    
        public virtual int lms_superadmin_update_department(Nullable<long> depId, string departmentName, ObjectParameter retVal)
        {
            var depIdParameter = depId.HasValue ?
                new ObjectParameter("DepId", depId) :
                new ObjectParameter("DepId", typeof(long));
    
            var departmentNameParameter = departmentName != null ?
                new ObjectParameter("departmentName", departmentName) :
                new ObjectParameter("departmentName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_department", depIdParameter, departmentNameParameter, retVal);
        }
    
        public virtual int lms_superadmin_update_LearnerInfo(Nullable<long> learner, string firstname, string surname, string email, Nullable<long> location, Nullable<long> department, ObjectParameter retval)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(long));
    
            var departmentParameter = department.HasValue ?
                new ObjectParameter("department", department) :
                new ObjectParameter("department", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_LearnerInfo", learnerParameter, firstnameParameter, surnameParameter, emailParameter, locationParameter, departmentParameter, retval);
        }
    
        public virtual int lms_superadmin_update_LearnerStatus(Nullable<long> learner, Nullable<bool> status, ObjectParameter retval)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_LearnerStatus", learnerParameter, statusParameter, retval);
        }
    
        public virtual int lms_superadmin_update_location(Nullable<long> locId, string locationName, ObjectParameter retVal)
        {
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(long));
    
            var locationNameParameter = locationName != null ?
                new ObjectParameter("locationName", locationName) :
                new ObjectParameter("locationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_location", locIdParameter, locationNameParameter, retVal);
        }
    
        public virtual int lms_superadmin_update_RAQuestionOption(Nullable<long> optionid, string option, Nullable<int> order, Nullable<bool> issue, ObjectParameter retval)
        {
            var optionidParameter = optionid.HasValue ?
                new ObjectParameter("optionid", optionid) :
                new ObjectParameter("optionid", typeof(long));
    
            var optionParameter = option != null ?
                new ObjectParameter("option", option) :
                new ObjectParameter("option", typeof(string));
    
            var orderParameter = order.HasValue ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(int));
    
            var issueParameter = issue.HasValue ?
                new ObjectParameter("issue", issue) :
                new ObjectParameter("issue", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_RAQuestionOption", optionidParameter, optionParameter, orderParameter, issueParameter, retval);
        }
    
        public virtual int lms_superadmin_update_RiskAssessmentGroup(Nullable<long> raid, string groupName, ObjectParameter retval)
        {
            var raidParameter = raid.HasValue ?
                new ObjectParameter("raid", raid) :
                new ObjectParameter("raid", typeof(long));
    
            var groupNameParameter = groupName != null ?
                new ObjectParameter("groupName", groupName) :
                new ObjectParameter("groupName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_RiskAssessmentGroup", raidParameter, groupNameParameter, retval);
        }
    
        public virtual int lms_superadmin_update_RiskAssessmentResult(Nullable<long> raid, Nullable<bool> signedOff, Nullable<long> adminId, string adminComment, ObjectParameter retval)
        {
            var raidParameter = raid.HasValue ?
                new ObjectParameter("raid", raid) :
                new ObjectParameter("raid", typeof(long));
    
            var signedOffParameter = signedOff.HasValue ?
                new ObjectParameter("signedOff", signedOff) :
                new ObjectParameter("signedOff", typeof(bool));
    
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("adminId", adminId) :
                new ObjectParameter("adminId", typeof(long));
    
            var adminCommentParameter = adminComment != null ?
                new ObjectParameter("adminComment", adminComment) :
                new ObjectParameter("adminComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_RiskAssessmentResult", raidParameter, signedOffParameter, adminIdParameter, adminCommentParameter, retval);
        }
    
        public virtual int lms_superadmin_UpdatetbCourseLicenseDetails(Nullable<int> licenseCourseId, Nullable<System.DateTime> licenseExpiryDate, Nullable<int> assignedLicenses)
        {
            var licenseCourseIdParameter = licenseCourseId.HasValue ?
                new ObjectParameter("LicenseCourseId", licenseCourseId) :
                new ObjectParameter("LicenseCourseId", typeof(int));
    
            var licenseExpiryDateParameter = licenseExpiryDate.HasValue ?
                new ObjectParameter("LicenseExpiryDate", licenseExpiryDate) :
                new ObjectParameter("LicenseExpiryDate", typeof(System.DateTime));
    
            var assignedLicensesParameter = assignedLicenses.HasValue ?
                new ObjectParameter("AssignedLicenses", assignedLicenses) :
                new ObjectParameter("AssignedLicenses", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_UpdatetbCourseLicenseDetails", licenseCourseIdParameter, licenseExpiryDateParameter, assignedLicensesParameter);
        }
    
        public virtual int lms_superadmin_create_OTP_record(Nullable<long> adminid, string otp, ObjectParameter retVal)
        {
            var adminidParameter = adminid.HasValue ?
                new ObjectParameter("adminid", adminid) :
                new ObjectParameter("adminid", typeof(long));
    
            var otpParameter = otp != null ?
                new ObjectParameter("otp", otp) :
                new ObjectParameter("otp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_create_OTP_record", adminidParameter, otpParameter, retVal);
        }
    
        public virtual int lms_superadmin_delete_location(Nullable<long> locId, ObjectParameter retVal)
        {
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_delete_location", locIdParameter, retVal);
        }
    
        public virtual ObjectResult<lms_superadmin_get_AboutToExpiryCompanies_NextWeek_Result> lms_superadmin_get_AboutToExpiryCompanies_NextWeek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_AboutToExpiryCompanies_NextWeek_Result>("lms_superadmin_get_AboutToExpiryCompanies_NextWeek");
        }
    
        public virtual ObjectResult<lms_superadmin_get_AllCourses_Result> lms_superadmin_get_AllCourses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_AllCourses_Result>("lms_superadmin_get_AllCourses");
        }
    
        public virtual ObjectResult<lms_superadmin_get_AllRACourseQuestions_Result> lms_superadmin_get_AllRACourseQuestions(Nullable<long> course)
        {
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_AllRACourseQuestions_Result>("lms_superadmin_get_AllRACourseQuestions", courseParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_AllRiskAssessments_Result> lms_superadmin_get_AllRiskAssessments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_AllRiskAssessments_Result>("lms_superadmin_get_AllRiskAssessments");
        }
    
        public virtual ObjectResult<Nullable<long>> lms_superadmin_get_company_by_sequential_id(string sequentialId)
        {
            var sequentialIdParameter = sequentialId != null ?
                new ObjectParameter("sequentialId", sequentialId) :
                new ObjectParameter("sequentialId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("lms_superadmin_get_company_by_sequential_id", sequentialIdParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_CompanyAdminInfo_Result> lms_superadmin_get_CompanyAdminInfo(string organisation)
        {
            var organisationParameter = organisation != null ?
                new ObjectParameter("organisation", organisation) :
                new ObjectParameter("organisation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_CompanyAdminInfo_Result>("lms_superadmin_get_CompanyAdminInfo", organisationParameter);
        }
    
        public virtual ObjectResult<byte[]> lms_superadmin_get_companyBanner(string orgUID)
        {
            var orgUIDParameter = orgUID != null ?
                new ObjectParameter("orgUID", orgUID) :
                new ObjectParameter("orgUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("lms_superadmin_get_companyBanner", orgUIDParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_CompnayLocationDepartmentMap_Result> lms_superadmin_get_CompnayLocationDepartmentMap(Nullable<long> location, string search)
        {
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(long));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_CompnayLocationDepartmentMap_Result>("lms_superadmin_get_CompnayLocationDepartmentMap", locationParameter, searchParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_crm_company_admin_Listing_Result> lms_superadmin_get_crm_company_admin_Listing(string selectedOrganisations, string selectedAdminTypes, Nullable<int> selectContractManager, Nullable<int> selectTrainer)
        {
            var selectedOrganisationsParameter = selectedOrganisations != null ?
                new ObjectParameter("selectedOrganisations", selectedOrganisations) :
                new ObjectParameter("selectedOrganisations", typeof(string));
    
            var selectedAdminTypesParameter = selectedAdminTypes != null ?
                new ObjectParameter("selectedAdminTypes", selectedAdminTypes) :
                new ObjectParameter("selectedAdminTypes", typeof(string));
    
            var selectContractManagerParameter = selectContractManager.HasValue ?
                new ObjectParameter("selectContractManager", selectContractManager) :
                new ObjectParameter("selectContractManager", typeof(int));
    
            var selectTrainerParameter = selectTrainer.HasValue ?
                new ObjectParameter("selectTrainer", selectTrainer) :
                new ObjectParameter("selectTrainer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_crm_company_admin_Listing_Result>("lms_superadmin_get_crm_company_admin_Listing", selectedOrganisationsParameter, selectedAdminTypesParameter, selectContractManagerParameter, selectTrainerParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_dash_HeaderInfo_Result> lms_superadmin_get_dash_HeaderInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_dash_HeaderInfo_Result>("lms_superadmin_get_dash_HeaderInfo");
        }
    
        public virtual ObjectResult<lms_superadmin_get_GroupsOfRA_Result> lms_superadmin_get_GroupsOfRA(Nullable<long> raid, string search)
        {
            var raidParameter = raid.HasValue ?
                new ObjectParameter("raid", raid) :
                new ObjectParameter("raid", typeof(long));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_GroupsOfRA_Result>("lms_superadmin_get_GroupsOfRA", raidParameter, searchParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_LearnerInfo_Result> lms_superadmin_get_LearnerInfo(Nullable<long> learner)
        {
            var learnerParameter = learner.HasValue ?
                new ObjectParameter("learner", learner) :
                new ObjectParameter("learner", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_LearnerInfo_Result>("lms_superadmin_get_LearnerInfo", learnerParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_LearnerRAReport_Result> lms_superadmin_get_LearnerRAReport(string learnerName, string companyName, Nullable<long> course, Nullable<int> signedOff, Nullable<int> issues, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string sortCol, string sortDir)
        {
            var learnerNameParameter = learnerName != null ?
                new ObjectParameter("learnerName", learnerName) :
                new ObjectParameter("learnerName", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            var signedOffParameter = signedOff.HasValue ?
                new ObjectParameter("signedOff", signedOff) :
                new ObjectParameter("signedOff", typeof(int));
    
            var issuesParameter = issues.HasValue ?
                new ObjectParameter("issues", issues) :
                new ObjectParameter("issues", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_LearnerRAReport_Result>("lms_superadmin_get_LearnerRAReport", learnerNameParameter, companyNameParameter, courseParameter, signedOffParameter, issuesParameter, fromDateParameter, toDateParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual ObjectResult<lms_superadmin_get_RAListing_Result> lms_superadmin_get_RAListing(string moduleName, Nullable<int> status, string sortCol, string sortDir)
        {
            var moduleNameParameter = moduleName != null ?
                new ObjectParameter("moduleName", moduleName) :
                new ObjectParameter("moduleName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_RAListing_Result>("lms_superadmin_get_RAListing", moduleNameParameter, statusParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual int lms_superadmin_update_learning_progress_record(Nullable<long> recordId, Nullable<int> score, Nullable<System.DateTime> completeionDate, string status, ObjectParameter retval)
        {
            var recordIdParameter = recordId.HasValue ?
                new ObjectParameter("recordId", recordId) :
                new ObjectParameter("recordId", typeof(long));
    
            var scoreParameter = score.HasValue ?
                new ObjectParameter("score", score) :
                new ObjectParameter("score", typeof(int));
    
            var completeionDateParameter = completeionDate.HasValue ?
                new ObjectParameter("completeionDate", completeionDate) :
                new ObjectParameter("completeionDate", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_learning_progress_record", recordIdParameter, scoreParameter, completeionDateParameter, statusParameter, retval);
        }
    
        public virtual int lms_superadmin_update_RAQuestion(string question, Nullable<long> questionid, Nullable<long> group, string groupText, Nullable<long> course, Nullable<int> order, ObjectParameter retval)
        {
            var questionParameter = question != null ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(string));
    
            var questionidParameter = questionid.HasValue ?
                new ObjectParameter("questionid", questionid) :
                new ObjectParameter("questionid", typeof(long));
    
            var groupParameter = group.HasValue ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(long));
    
            var groupTextParameter = groupText != null ?
                new ObjectParameter("groupText", groupText) :
                new ObjectParameter("groupText", typeof(string));
    
            var courseParameter = course.HasValue ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(long));
    
            var orderParameter = order.HasValue ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_superadmin_update_RAQuestion", questionParameter, questionidParameter, groupParameter, groupTextParameter, courseParameter, orderParameter, retval);
        }
    
        public virtual ObjectResult<lms_superadmin_get_courseListing_Result> lms_superadmin_get_courseListing(string courseName, Nullable<int> status, string sortCol, string sortDir)
        {
            var courseNameParameter = courseName != null ?
                new ObjectParameter("courseName", courseName) :
                new ObjectParameter("courseName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var sortColParameter = sortCol != null ?
                new ObjectParameter("sortCol", sortCol) :
                new ObjectParameter("sortCol", typeof(string));
    
            var sortDirParameter = sortDir != null ?
                new ObjectParameter("sortDir", sortDir) :
                new ObjectParameter("sortDir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_superadmin_get_courseListing_Result>("lms_superadmin_get_courseListing", courseNameParameter, statusParameter, sortColParameter, sortDirParameter);
        }
    
        public virtual int lms_api_AddLicense(string userId, string courseId, string licenseKey, Nullable<System.DateTime> expiryDate, string status)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var courseIdParameter = courseId != null ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(string));
    
            var licenseKeyParameter = licenseKey != null ?
                new ObjectParameter("LicenseKey", licenseKey) :
                new ObjectParameter("LicenseKey", typeof(string));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_api_AddLicense", userIdParameter, courseIdParameter, licenseKeyParameter, expiryDateParameter, statusParameter);
        }
    
        public virtual ObjectResult<lms_api_GetLicense_Result> lms_api_GetLicense(string userId, string courseId, string licence)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var courseIdParameter = courseId != null ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(string));
    
            var licenceParameter = licence != null ?
                new ObjectParameter("Licence", licence) :
                new ObjectParameter("Licence", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_api_GetLicense_Result>("lms_api_GetLicense", userIdParameter, courseIdParameter, licenceParameter);
        }
    
        public virtual int lms_api_RenewLicense(Nullable<int> licenseId, Nullable<System.DateTime> newExpiryDate)
        {
            var licenseIdParameter = licenseId.HasValue ?
                new ObjectParameter("LicenseId", licenseId) :
                new ObjectParameter("LicenseId", typeof(int));
    
            var newExpiryDateParameter = newExpiryDate.HasValue ?
                new ObjectParameter("NewExpiryDate", newExpiryDate) :
                new ObjectParameter("NewExpiryDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_api_RenewLicense", licenseIdParameter, newExpiryDateParameter);
        }
    
        public virtual int lms_api_RevokeLicense(Nullable<int> licenseId)
        {
            var licenseIdParameter = licenseId.HasValue ?
                new ObjectParameter("LicenseId", licenseId) :
                new ObjectParameter("LicenseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lms_api_RevokeLicense", licenseIdParameter);
        }
    
        public virtual ObjectResult<lms_api_GetLicenseByKey_Result> lms_api_GetLicenseByKey(string licenseKey, string courseId)
        {
            var licenseKeyParameter = licenseKey != null ?
                new ObjectParameter("LicenseKey", licenseKey) :
                new ObjectParameter("LicenseKey", typeof(string));
    
            var courseIdParameter = courseId != null ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lms_api_GetLicenseByKey_Result>("lms_api_GetLicenseByKey", licenseKeyParameter, courseIdParameter);
        }
    }
}
